### ISSUE TITLE
concurrencyのロック待ちをsleep loopより賢くする

### ISSUE THREAD

**Issue by yokomotod** [yokomotod/database-design-and-implementation-go#4]
該当箇所: https://github.com/yokomotod/database-design-and-implementation-go/pull/3/files#diff-48fb7115fb71adf25725a6d19ba68b5e0aa56c795e341ebf02aea88f6d4b7ee0R27

Javaでは `wait()` / `notify()` が使われている

Goなら [sync.Cond](https://pkg.go.dev/sync#Cond) ?

**Comment by ma2gedev** [comment]
#7 をマージしたのでこちらもクローズします
